apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-main-customer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  labels:
    app.kubernetes.io/part-of: yas
    yas.dev/logical-environment: main
    yas.dev/source-branch: main
spec:
  project: yas
  source:
    repoURL: https://github.com/TrNhDuong/yas_devops.git
    targetRevision: main
    path: k8s/charts/customer
    helm:
      releaseName: customer
      parameters:
      - name: backend.image.repository
        value: nguyenmanhha/yas-customer
      - name: backend.image.tag
        value: aa2459cdeadb37cd4368d3c2c6a72d9ada512833
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
