apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-main-backoffice-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  labels:
    app.kubernetes.io/part-of: yas
    yas.dev/logical-environment: main
    yas.dev/source-branch: main
spec:
  project: yas
  source:
    repoURL: https://github.com/TrNhDuong/yas_devops.git
    targetRevision: main
    path: k8s/charts/backoffice-ui
    helm:
      releaseName: backoffice-ui
      parameters:
      - name: ui.image.repository
        value: nguyenmanhha/yas-backoffice
      - name: ui.image.tag
        value: 8da87551b484a8125166aa9289aa6e7b0267da47
      - name: ui.ingress.enabled
        value: 'false'
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
