apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-media
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/media"
    helm:
      releaseName: "media"
      parameters:
        - name: "backend.image.repository"
          value: "nguyenmanhha/yas-media"
        - name: "backend.image.tag"
          value: "aa2459cdeadb37cd4368d3c2c6a72d9ada512833"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
