apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-tax
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/tax"
    helm:
      releaseName: "tax"
      parameters:
        - name: "backend.image.repository"
          value: "nguyenmanhha/yas-tax"
        - name: "backend.image.tag"
          value: "4af0969a83fb900851268d35a692333c5938b1b2"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
