apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-search
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/part-of: yas
    yas.dev/logical-environment: staging
    yas.dev/release-channel: git-tag
spec:
  project: yas
  source:
    repoURL: https://github.com/TrNhDuong/yas_devops.git
    targetRevision: main
    path: k8s/charts/search
    helm:
      releaseName: search
      parameters:
      - name: backend.image.repository
        value: "nguyenmanhha/yas-search"
      - name: backend.image.tag
        value: "59f86e7f3d7281cc61d5f26896af8ef8726e1a15"
      - name: backend.extraEnvs[0].name
        value: SPRING_ELASTICSEARCH_URIS
      - name: backend.extraEnvs[0].value
        value: http://elasticsearch-es-http.elasticsearch:9200
        forceString: true
      - name: backend.extraEnvs[1].name
        value: SPRING_ELASTICSEARCH_USERNAME
      - name: backend.extraEnvs[1].valueFrom.secretKeyRef.name
        value: search-elasticsearch-credentials
      - name: backend.extraEnvs[1].valueFrom.secretKeyRef.key
        value: username
      - name: backend.extraEnvs[2].name
        value: SPRING_ELASTICSEARCH_PASSWORD
      - name: backend.extraEnvs[2].valueFrom.secretKeyRef.name
        value: search-elasticsearch-credentials
      - name: backend.extraEnvs[2].valueFrom.secretKeyRef.key
        value: password
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
