apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-sampledata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/sampledata"
    helm:
      parameters:
        - name: "backend.image.repository"
          value: "nguyenmanhha/yas-sampledata"
        - name: "backend.image.tag"
          value: "latest"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
