apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-sampledata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/sampledata"
    helm:
      releaseName: "sampledata"
      parameters:
        - name: "backend.image.repository"
          value: "nguyenmanhha/yas-sampledata"
        - name: "backend.image.tag"
          value: "558aaf7281ed0585a83e9ca97b44b7cd040d411d"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
