apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-storefront-bff
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://github.com/Duong-Dung/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/storefront-bff"
    helm:
      releaseName: "storefront-bff"
      parameters:
        - name: "backend.image.repository"
          value: "nguyenmanhha/yas-storefront-bff"
        - name: "backend.image.tag"
          value: "main"
        - name: "backend.ingress.enabled"
          value: "true"
        - name: "backend.ingress.host"
          value: "storefront.staging.yas.local.com"
          forceString: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
