apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-storefront-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/storefront-ui"
    helm:
      releaseName: "storefront-ui"
      parameters:
        - name: "ui.image.repository"
          value: "nguyenmanhha/yas-storefront"
        - name: "ui.image.tag"
          value: "13e7845e2bbd1c7422c99489abe3939e978974d2"
        - name: "ui.extraEnvs[0].name"
          value: "API_BASE_PATH"
        - name: "ui.extraEnvs[0].value"
          value: "http://storefront.staging.yas.local.com/api"
          forceString: true
        - name: "ui.ingress.enabled"
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
