apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-backoffice-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://github.com/TrNhDuong/yas_devops.git"
    targetRevision: "fix/k8s-minikube-yas-deploy"
    path: "k8s/charts/backoffice-ui"
    helm:
      releaseName: "backoffice-ui"
      parameters:
        - name: "ui.image.repository"
          value: "nguyenmanhha/yas-backoffice"
        - name: "ui.image.tag"
          value: "8da87551b484a8125166aa9289aa6e7b0267da47"
        - name: "ui.ingress.enabled"
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "yas-staging"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
