apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-swagger-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  labels:
    app.kubernetes.io/part-of: yas
    yas.dev/logical-environment: staging
    yas.dev/release-channel: git-tag
spec:
  project: yas
  source:
    repoURL: https://github.com/TrNhDuong/yas_devops.git
    targetRevision: main
    path: k8s/charts/swagger-ui
    helm:
      releaseName: swagger-ui
      parameters:
      - name: ingress.enabled
        value: 'true'
      - name: ingress.className
        value: nginx
      - name: ingress.host
        value: api.staging.yas.local.com
        forceString: true
      - name: ingress.hosts[0].host
        value: api.staging.yas.local.com
        forceString: true
      - name: ingress.hosts[0].paths[0].path
        value: /swagger-ui
        forceString: true
      - name: ingress.hosts[0].paths[0].pathType
        value: ImplementationSpecific
      - name: urls
        value: '[{ url: ''http://api.staging.yas.local.com/product/v3/api-docs'',
          name: ''Product'' }, { url: ''http://api.staging.yas.local.com/media/v3/api-docs'',
          name: ''Media'' }, { url: ''http://api.staging.yas.local.com/customer/v3/api-docs'',
          name: ''Customer'' }, { url: ''http://api.staging.yas.local.com/cart/v3/api-docs'',
          name: ''Cart'' }, { url: ''http://api.staging.yas.local.com/order/v3/api-docs'',
          name: ''Order'' }, { url: ''http://api.staging.yas.local.com/inventory/v3/api-docs'',
          name: ''Inventory'' }, { url: ''http://api.staging.yas.local.com/tax/v3/api-docs'',
          name: ''Tax'' }, { url: ''http://api.staging.yas.local.com/search/v3/api-docs'',
          name: ''Search'' }]'
        forceString: true
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
